import { AppState, Permission } from "./types";

export const allPermissions: Permission[] = [
  "dashboard",
  "guests",
  "rooms",
  "services",
  "staff",
  "expenses",
  "housekeeping",
  "billing",
  "accounting",
  "inventory",
  "analytics",
  "safety",
  "users",
];

export const initialState: AppState = {
  users: [
    {
      id: "u-1",
      name: "Main Admin",
      username: "admin",
      password: "Admin@123",
      role: "admin",
      permissions: allPermissions,
    },
    {
      id: "u-2",
      name: "Front Desk Lead",
      username: "frontdesk",
      password: "Frontdesk@123",
      role: "parent-admin",
      permissions: ["dashboard", "guests", "rooms", "services", "billing"],
    },
  ],
  guests: [
    {
      id: "g-101",
      name: "Arjun Mehta",
      phone: "+91 90000 11111",
      idProof: "Aadhaar uploaded",
      roomPreference: "Deluxe",
      serviceTiming: "Breakfast 8:00 AM",
      returning: true,
      emergencyContact: "Riya Mehta / +91 95555 11111",
      status: "checked-in",
      roomId: "R-103",
    },
    {
      id: "g-102",
      name: "Neha Kapoor",
      phone: "+91 90000 22222",
      idProof: "Passport uploaded",
      roomPreference: "Suite",
      serviceTiming: "Tea 5:30 PM",
      returning: false,
      emergencyContact: "Aman Kapoor / +91 96666 22222",
      status: "reserved",
    },
  ],
  rooms: [
    {
      id: "R-101",
      number: "101",
      type: "Standard",
      price: 2200,
      status: "vacant",
      lastGuest: "Priya S",
    },
    {
      id: "R-102",
      number: "102",
      type: "Deluxe",
      price: 3200,
      status: "reserved",
      lastGuest: "Kunal V",
    },
    {
      id: "R-103",
      number: "103",
      type: "Deluxe",
      price: 3400,
      status: "occupied",
      lastGuest: "Arjun Mehta",
    },
    {
      id: "R-201",
      number: "201",
      type: "Suite",
      price: 4800,
      status: "blocked",
      lastGuest: "N/A",
    },
  ],
  services: [
    {
      day: "Monday",
      breakfast: "Poha, fruit bowl, tea",
      tea: "Masala tea and cookies",
      timing: "7:30 AM - 10:00 AM",
      billAmount: 180,
    },
    {
      day: "Tuesday",
      breakfast: "Idli, chutney, coffee",
      tea: "Green tea and khari",
      timing: "7:30 AM - 10:00 AM",
      billAmount: 190,
    },
    {
      day: "Wednesday",
      breakfast: "Paratha, curd, tea",
      tea: "Lemon tea and toast",
      timing: "7:30 AM - 10:00 AM",
      billAmount: 210,
    },
  ],
  staff: [
    {
      id: "s-1",
      name: "Pooja",
      role: "Reception",
      shift: "7:00 AM - 3:00 PM",
      attendance: "Present",
      task: "Check-in desk",
    },
    {
      id: "s-2",
      name: "Ramesh",
      role: "Housekeeping",
      shift: "9:00 AM - 5:00 PM",
      attendance: "Late",
      task: "Floor 2 cleaning",
    },
    {
      id: "s-3",
      name: "Anil",
      role: "Security",
      shift: "10:00 PM - 6:00 AM",
      attendance: "Present",
      task: "Night patrol",
    },
  ],
  expenses: [
    {
      id: "e-1",
      label: "Laundry supplies",
      category: "Supplies",
      amount: 3200,
      date: "2026-04-10",
    },
    {
      id: "e-2",
      label: "Water bill",
      category: "Utility",
      amount: 8450,
      date: "2026-04-09",
    },
    {
      id: "e-3",
      label: "AC maintenance",
      category: "Maintenance",
      amount: 5600,
      date: "2026-04-07",
    },
  ],
  housekeeping: [
    {
      roomNumber: "101",
      status: "cleaned",
      laundry: "2 sheets pending pickup",
      note: "Ready for check-in",
    },
    {
      roomNumber: "102",
      status: "pending",
      laundry: "Fresh towels required",
      note: "Guest arriving at 6 PM",
    },
    {
      roomNumber: "103",
      status: "in-progress",
      laundry: "No issues",
      note: "Auto-alert after checkout enabled",
    },
  ],
  invoices: [
    {
      id: "inv-1001",
      guestName: "Arjun Mehta",
      amount: 8240,
      tax: 1483,
      paymentMode: "UPI",
      status: "Paid",
    },
    {
      id: "inv-1002",
      guestName: "Neha Kapoor",
      amount: 5660,
      tax: 1018,
      paymentMode: "Card",
      status: "Pending",
    },
  ],
  inventory: [
    {
      id: "i-1",
      name: "Bath towels",
      stock: 34,
      minimum: 18,
      unit: "pcs",
    },
    {
      id: "i-2",
      name: "Bedsheets",
      stock: 22,
      minimum: 20,
      unit: "pcs",
    },
    {
      id: "i-3",
      name: "Toiletry kits",
      stock: 11,
      minimum: 15,
      unit: "packs",
    },
    {
      id: "i-4",
      name: "Tea sachets",
      stock: 42,
      minimum: 25,
      unit: "boxes",
    },
  ],
  safety: [
    {
      id: "sf-1",
      title: "Fire extinguisher inspection",
      owner: "Security",
      status: "Due",
    },
    {
      id: "sf-2",
      title: "Emergency doctor list update",
      owner: "Reception",
      status: "Done",
    },
    {
      id: "sf-3",
      title: "Exit signage checklist",
      owner: "Maintenance",
      status: "Urgent",
    },
  ],
};
